hivemind/blueprints/auth.py
from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from flask_login import login_required, login_user, logout_user

from hivemind.forms import LoginForm, SignupForm
from hivemind.models import User
from hivemind.core.extensions import db

auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = request.form.get('username').strip()
        password = request.form.get('password').strip()
        user: User = db.session.execute(db.select(User).where(User.username == username)).scalars().first()

        try:
            if user.username == username and user.validate_password(password):
                login_user(user)
                return redirect(url_for('main.index'))
            else:
                flash('User doesnt exist or password is incorrect.', 'error')
                return redirect(url_for('auth.login'))
            
        except Exception as e:
            flash(f'Login failed! Error: {e}', 'error')
            return redirect(url_for('auth.login'))

    return render_template('login.html', form=form)

@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        username = request.form.get('username')
        name = request.form.get('name')
        password = request.form.get('password')
        exists = db.session.execute(db.select(User).where(User.username == username)).scalars().first()
        
        if not exists:
            user = User(username=username, name=name)
            user.set_password(password)
            db.session.add(user)
            db.session.commit()
            flash('User successfully created! Please sign in.', 'success')        
            return redirect(url_for('auth.login'))
        else:
            flash('User already exists, please use a different username.', 'error')     
            return redirect(url_for('auth.signup'))
        
    return render_template('signup.html', form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Goodbye!')
    return redirect(url_for('auth.login'))

hivemind/blueprints/hive.py
from flask import Blueprint, flash, redirect, render_template, session, url_for
from flask_login import login_required
from hivemind.core.extensions import db
from hivemind.models import ChatMessage, Chatroom, ChatroomParticipant, User

hive_bp = Blueprint('hive', __name__, url_prefix='/hive')

@hive_bp.route('/room/<int:chatroom_id>')
@login_required
def hive(chatroom_id):
    chatroom = db.session.execute(db.select(Chatroom).where(Chatroom.id == chatroom_id)).scalars().first()
    if chatroom:
        participants = db.session.execute(db.select(User)
                                           .join(ChatroomParticipant, User.id == ChatroomParticipant.user_id)
                                           .where(ChatroomParticipant.chatroom_id == chatroom_id)).scalars().all()
        chat_messages = db.session.execute(db.select(ChatMessage).where(ChatMessage.chatroom_id == chatroom_id)).scalars().all()
        
        return render_template('hive.html', chatroom_id=chatroom_id, chat_messages=chat_messages, participants=participants)
    else:
        flash("Chatroom doesn't exist!", 'error')
        return redirect(url_for('main.index'))

hivemind/blueprints/settings.py
import os
from flask import Blueprint, current_app, flash, redirect, render_template, session, url_for
from flask_login import current_user, login_required
from flask_socketio import emit

from hivemind.forms import AvatarForm, ProfileForm
from hivemind.models import User
from hivemind.core.extensions import db, avatars

settings_bp = Blueprint('settings', __name__, url_prefix='/settings')
DEFAULT_AVATARS_PATH = 'avatars/default.jpg'

@settings_bp.route('/upload-avatar', methods=['GET', 'POST'])
@login_required
def upload_avatar():
    form = AvatarForm()
    
    if form.validate_on_submit():
        if current_user.profile_picture != DEFAULT_AVATARS_PATH:
            try:
                filepath = os.path.join(current_app.static_folder, current_user.profile_picture)
                os.remove(filepath)
            except OSError:
                flash("Filename doesn't exist!", 'error')
                
        filename = avatars.save(form.avatar.data, name=f'{current_user.id}.')
        print('avatars/' + filename, flush=True)
        current_user.set_profile_picture('avatars/' + filename)
        db.session.commit()
        
        flash('Avatar succesfully updated!')
        return redirect(url_for('settings.upload_avatar'))
    
    return render_template('settings/upload_avatar.html', form=form)
        

@settings_bp.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    profile_form = ProfileForm()
    avatar_form = AvatarForm()
        
    if profile_form.validate_on_submit():
        new_name = profile_form.name.data
        new_username = profile_form.username.data
        
        exists = db.session.execute(db.select(User).where(User.username == new_username)).scalars().first()
        
        if exists and exists != current_user:
            flash("Username already taken!", "error")
            return redirect(url_for('.edit_profile'))
        
        current_user.name = new_name
        current_user.username = new_username
        db.session.commit()
        
        emit('update_profile', {
            'user': current_user.to_dict()
            }, namespace='/hive', 
                broadcast=True)
            
        flash('Profile updated!')
        return redirect(url_for('.edit_profile'))
    
    return render_template('settings/edit_profile.html', profile_form=profile_form, avatar_form=avatar_form)

hivemind/templates/base.html
{% set current_page = request.endpoint %}

<!DOCTYPE html>
<html {% block html_attribs %} data-theme="wireframe" {% endblock html_attribs %}>

<head>
  {%- block head %}
  <title>{% block title %}{% endblock title %}</title>
  {%- block metas %}
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8">
  {%- endblock metas %}
  {%- block styles %}
  <link rel="preload" href="{{ url_for('static', filename='css/output.css') }}" as="style">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/output.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}" type="text/css">
  {%- endblock styles %}
  {%- endblock head %}
</head>

<body {% block body_attribs %}{% endblock body_attribs %}>
  <div class="flex flex-col h-full">

    {% block navbar %}
    <div class="navbar container mx-auto bg-base-100">
      <div class="flex-1">
        <a class="btn btn-ghost text-xl" href="{{ url_for('main.index') }}">Hivemind</a>
      </div>
      <div class="flex-none gap-2">
        {% if current_user.is_authenticated %}
        <div> {{ current_user.name }} </div>
          <div class="dropdown dropdown-end">
            <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
              <div class="w-10 rounded-full">
                <img src="{{ url_for('static', filename=current_user.profile_picture) }}" />
              </div>
            </div>
            <ul tabindex="0" class="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow">
              <li><a href="{{ url_for('settings.edit_profile') }}">Settings</a></li>
              <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            </ul>
          </div>
        {% else %}
          {% if current_page != 'auth.login' %}
            <div>
              <a href="{{ url_for('auth.login') }}">Login</a>
            </div>
          {% endif %}
        {% endif %}
      </div>
    </div>
    {% endblock navbar %}

    {% for category, message in get_flashed_messages(with_categories=true) %}
    <div role="alert" id="alert" class="{{ 'alert alert-error container mx-auto' if category=='error' else 'alert alert-success container mx-auto' }}">
      <span>{{ message }}</span>
    </div>
    {% endfor %}

    {% block content %}
    {% endblock content%}

    {% block footer -%}
    <footer class="footer footer-center text-base-content">
      <ul class="menu menu-horizontal gap-0.5">
        <li class="text-xs">Copyright ©</li>
        <li><a class="text-xs p-2" href="https://github.com/ecar33">Evan Carlile</a></li>
      </ul>
    </footer>
    {% endblock footer %}

  </div>

  {% block scripts %}
  <script src="{{ url_for('static', filename='/js/base.js') }}" type="application/javascript"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  {%- endblock scripts %}
</body>

</html>

hivemind/templates/hive.html
{% extends 'base.html' %}


{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/hive.css') }}" type="text/css">
{% endblock styles %}

{% block navbar %}
{% endblock navbar %}

{% block content %}
<meta id="data" data-chatroom_id="{{ chatroom_id }}" data-name="{{ current_user.name }}" data-avatar="{{ url_for('static', filename=current_user.profile_picture) }}">

<div class="drawer lg:drawer-open">
  <input id="my-drawer" type="checkbox" class="drawer-toggle" />
  <div class="drawer-content">
    <div class="drawer h-dvh lg:drawer-open drawer-end">
      <input id="my-drawer-2" type="checkbox" class="drawer-toggle" />
      <div class="drawer-content flex flex-col justify-between">
        <div class="navbar bg-primary">
          <div class="mx-2 flex-1 px-2">Chatroom {{ chatroom_id }}</div>
          <div class="flex-none lg:hidden">
            <label for="my-drawer" aria-label="open sidebar" class="btn btn-square btn-ghost">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                class="inline-block h-6 w-6 stroke-current">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16">
                </path>
              </svg>
            </label>
            <label for="my-drawer-2" aria-label="open sidebar" class="btn btn-square btn-ghost">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round"
                  d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
              </svg>
            </label>
          </div>
          <div class="flex-none lg:block">
            <ul class="menu menu-horizontal">
              <!-- Navbar menu content here -->
              {% if current_user.is_authenticated %}
              <div class="flex items-center">
                <p class="text-center">{{ current_user.name }}</p>
                <div class="dropdown dropdown-end">
                  <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
                    <div class="w-10 rounded-full">
                      <img src="{{ url_for('static', filename=current_user.profile_picture) }}" />
                    </div>
                  </div>
                  <ul tabindex="0"
                    class="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow">
                    <li><a href="{{ url_for('settings.edit_profile') }}">Settings</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                  </ul>
                </div>
              </div>
              {% endif %}
            </ul>
          </div>
        </div>
        <!-- Page content here -->
        <div id="chat-message-container" class="flex flex-col scroll-smooth overflow-auto p-4 gap-4"
          style="height: calc(100vh - 9rem);">
          <!-- Message template for received messages -->
          <template id="rcv-message-template">
            <div class="chat chat-start">
              <div class="chat-image avatar">
                <div class="w-10 rounded-full">
                  <img class="chat-avatar" alt=""
                    src="" />
                </div>
              </div>
              <div class="chat-header">
                <time class="text-xs opacity-50">12:45</time>
              </div>
              <div class="chat-bubble"></div>
            </div>
          </template>

          <!-- Message template for sent messages -->
          <template id="snd-message-template">
            <div class="chat chat-end">
              <div class="chat-image avatar">
                <div class="w-10 rounded-full">
                  <img class="chat-avatar" alt=""
                    src="" />
                </div>
              </div>
              <div class="chat-header">
                <time class="text-xs opacity-50">12:45</time>
              </div>
              <div class="chat-bubble"></div>
            </div>
          </template>
          <!-- {% for message in chat_messages %}
            <div class="chat chat-start">
                <div class="chat-image avatar">
                <div class="w-10 rounded-full">
                    <img
                    alt="T"
                    src="" />
                </div>
                </div>
                <div class="chat-header">
                User {{ message.user_id }}
                <time class="text-xs opacity-50">12:45</time>
                </div>
                <div class="chat-bubble">{{ message.content }}</div>
            </div>
            {% endfor %} -->
        </div>
        <!-- Sticky Message Send Bar -->
        <div class="sticky bottom-0 p-4 shadow flex items-center gap-2">
          <input id="text" maxlength="2000" type="text" required title="1 to 2000 characters long."
            placeholder="Enter a message..." class="flex-1 p-2 border rounded" />
          <button id='send' class="p-2 bg-blue-500 text-white rounded pl-2">
            Send
          </button>
        </div>
      </div>
      <div class="drawer-side">
        <label for="my-drawer-2" aria-label="close sidebar" class="drawer-overlay"></label>
        <ul id="user_list"
          class="menu bg-base-200 text-base-content min-h-full w-64 overflow-auto scroll-smooth divide-y divide-gray-300 gap-2">
          <!-- Sidebar content here -->
          {% for user in participants %}
          <li data-user_id='{{ user.id }}' class="w-full">
            <div class="avatar">
              <div class="w-10 rounded-full">
                <img src="{{ url_for('static', filename=user.profile_picture) }}" />
              </div>
              <a class="user_sidebar_name"> {{ user.name }} </a>
          </li>
          {% endfor %}
          <!-- Template for adding new users to the sidebar -->
          <template id="user-sidebar-template">
            <li data-user_id='' class="w-full">
              <div class="avatar">
                <div class="w-10 rounded-full">
                  <img class='sidebar-avatar' src="" />
                </div>
                <a class="user_sidebar_name"></a>
            </li>
          </template>
        </ul>
      </div>
    </div>
  </div>
  <div class="drawer-side">
    <label for="my-drawer" aria-label="close sidebar" class="drawer-overlay"></label>
    <ul class="menu min-h-full w-64 bg-base-200 p-4 text-base-content overflow-auto">
      {% for chatroom in chatrooms %}
      <li><a href="{{ url_for('hive.hive', chatroom_id=chatroom.id) }}">Chatroom {{ chatroom.id }}</a>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock content%}

{% block footer %}
{% endblock footer %}

{% block scripts %}

{{ super() }}

<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
  integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
  crossorigin="anonymous"></script>

<script src="{{ url_for('static', filename='js/hive.js') }}"></script>

{% endblock scripts %}

hivemind/templates/index.html
{% extends 'base.html'%}

{% block content %}
<div class="container mx-auto flex-1 flex flex-col justify-center items-center">
    <h1 class="mb-2">Hivemind</h1>
    <ul class="menu bg-base-200 rounded-box w-56">
        {% for chatroom in chatrooms %}
        <li><a href="{{ url_for('hive.hive', chatroom_id=chatroom.id) }}"> Room {{ chatroom.id }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

hivemind/templates/login.html
{% extends 'base.html'%}

{% block content %}
<div class= "flex-1 flex flex-col justify-center items-center">
    <h1 class="mb-2">Hivemind</h1>
    <form method="POST" class="flex flex-col justify-center">
        {{ form.hidden_tag() }}
        <label class="input input-bordered flex items-center gap-2 mb-2">
            Username
            {{ form.username(class_="grow") }} {% for error in form.username.errors %}{{ error }}{% endfor %}<br>
        </label>
        <label class="input input-bordered flex items-center gap-2 mb-2">
            Password
            {{ form.password(class_="grow") }} {% for error in form.password.errors %}{{ error }}{% endfor %}<br>
        </label>
        {{ form.submit(class_="align-center btn w-44 self-center mt-2") }}
    </form>
</div>
{% endblock content %}

hivemind/templates/signup.html
{% extends 'base.html'%}

{% block content %}

<div class="flex-1 flex flex-col justify-center items-center">
    <h1 class="mb-2">Sign Up</h1>
    <form method="POST" class="flex flex-col justify-center">
        {{ form.hidden_tag() }}
        <label class="input input-bordered flex items-center gap-2 mb-2">
            Display Name
            {{ form.name(class_="grow") }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br>
        </label>
        <label class="input input-bordered flex items-center gap-2 mb-2">
            Username
            {{ form.username(class_="grow") }} {% for error in form.username.errors %}{{ error }}{% endfor %}<br>
        </label>
        <label class="input input-bordered flex items-center gap-2 mb-2">
            Password
            {{ form.password(class_="grow") }} {% for error in form.password.errors %}{{ error }}{% endfor %}<br>
        </label>
        <label class="input input-bordered flex items-center gap-2 mb-2">
            Confirm Password
            {{ form.confirm_password(class_="grow") }} {% for error in form.confirm_password.errors %}{{ error }}{% endfor %}<br>
        </label>
        {{ form.submit(class_="align-center btn w-44 self-center mt-2") }}
    </form>
</div>

{% endblock content %}